/** Gallery content mirrored from TAC_Main_Website_2026_27 src/data/home.ts */
window.HOME_GALLERY = {
  label: "Life on Campus",
  title: "A glimpse into everyday TACS",
  titleMobile: "A Glimpse Into Everyday TACS",
  tabs: [
    {
      id: "campus",
      label: "Campus",
      items: [
        { label: "Reading Room", height: 260, src: "images/home/gallery/campus-1.png", alt: "Students reading in the campus library at TACS" },
        { label: "Outdoor Learning", height: 320, src: "images/home/gallery/campus-2.png", alt: "Teacher leading an outdoor learning session on campus at TACS" },
        { label: "School Garden", height: 200, src: "images/home/gallery/campus-3.png", alt: "Students working in the school garden at TACS" },
        { label: "Campus Dining", height: 220, src: "images/home/gallery/campus-4.png", alt: "A meal served in the campus dining hall at TACS" },
        { label: "Badminton", height: 300, src: "images/home/gallery/campus-5.png", alt: "Students playing badminton on campus at TACS" },
        { label: "Volleyball", height: 280, src: "images/home/gallery/campus-6.png", alt: "Students playing volleyball on the campus courts at TACS" },
        { label: "Science Lab", height: 200, src: "images/home/gallery/campus-7.png", alt: "Students using a microscope in the campus science lab at TACS" },
        { label: "Adventure Sports", height: 240, src: "images/home/gallery/campus-8.png", alt: "Students enjoying adventure sports on campus at TACS" },
      ],
    },
    {
      id: "infrastructure",
      label: "Infrastructure",
      layout: "featured-grid",
      items: [
        { label: "Campus Aerial View", height: 576, src: "images/home/gallery/infrastructure-aerial.png", alt: "Aerial view of The Academic City School campus in Bengaluru" },
        { label: "Outdoor Amphitheater", height: 200, src: "images/home/gallery/infrastructure-1.png", alt: "Outdoor amphitheater at The Academic City School campus" },
        { label: "Chemistry Lab", height: 260, src: "images/home/gallery/infrastructure-2.png", alt: "Chemistry laboratory at TACS" },
        { label: "Hostel Rooms", height: 220, src: "images/home/gallery/infrastructure-3.png", alt: "Modern hostel rooms at TACS" },
        { label: "Physics Lab", height: 240, src: "images/home/gallery/infrastructure-4.png", alt: "Physics laboratory at TACS" },
        { label: "Swimming Pool", height: 320, src: "images/home/gallery/infrastructure-5.png", alt: "Swimming pool at TACS" },
        { label: "Montessori Lab", height: 180, src: "images/home/gallery/infrastructure-6.png", alt: "Montessori learning lab at TACS" },
        { label: "Biology Lab", height: 260, src: "images/home/gallery/infrastructure-7.png", alt: "Biology laboratory at TACS" },
        { label: "Academic Blocks", height: 200, src: "images/home/gallery/infrastructure-8.png", alt: "Academic blocks at TACS campus" },
        { label: "Goshala", height: 300, src: "images/home/gallery/infrastructure-9.png", alt: "Goshala and campus farm at TACS" },
        { label: "Dining Hall", height: 220, src: "images/home/gallery/infrastructure-10.png", alt: "Dining hall at TACS" },
        { label: "Art Studio", height: 180, src: "images/home/gallery/infrastructure-11.png", alt: "Art studio at TACS" },
        { label: "Smart Classroom", height: 280, src: "images/home/gallery/infrastructure-12.png", alt: "Smart classroom at TACS" },
      ],
    },
    {
      id: "academics",
      label: "Academics",
      items: [
        { label: "Interactive Teaching", height: 180, src: "images/home/gallery/academics-5.png", alt: "Teacher leading an interactive classroom session at TACS" },
        { label: "Smart Classroom", height: 260, src: "images/home/gallery/academics-1.png", alt: "Students learning together in a smart classroom at TACS" },
        { label: "Classroom Learning", height: 320, src: "images/home/gallery/academics-2.png", alt: "Student taking notes during classroom learning at TACS" },
        { label: "Library", height: 280, src: "images/home/gallery/academics-7.png", alt: "Students browsing books in the TACS library" },
        { label: "Science Lab", height: 200, src: "images/home/gallery/academics-3.png", alt: "Students using a microscope in the science lab at TACS" },
        { label: "Academic Focus", height: 220, src: "images/home/gallery/academics-4.png", alt: "Student focused on learning in the classroom at TACS" },
        { label: "Chemistry Lab", height: 300, src: "images/home/gallery/academics-6.png", alt: "Students conducting a chemistry experiment at TACS" },
        { label: "Classroom Session", height: 240, src: "images/home/gallery/academics-8.png", alt: "Teacher addressing students during a classroom session at TACS" },
      ],
    },
    {
      id: "extra",
      label: "Extra-curriculars",
      items: [
        { label: "Reading Corner", height: 240, src: "images/home/gallery/extra-8.png", alt: "Student reading in the campus library at TACS" },
        { label: "Fine Arts", height: 260, src: "images/home/gallery/extra-2.png", alt: "Students practising portrait drawing in the fine arts studio at TACS" },
        { label: "Music Class", height: 220, src: "images/home/gallery/extra-3.png", alt: "Students learning keyboard and guitar in music class at TACS" },
        { label: "Painting", height: 200, src: "images/home/gallery/extra-5.png", alt: "Student painting during an art session at TACS" },
        { label: "Dahi Handi", height: 280, src: "images/home/gallery/extra-6.png", alt: "Students celebrating Dahi Handi on campus at TACS" },
        { label: "Kannada Rajyotsava", height: 320, src: "images/home/gallery/extra-7.png", alt: "Traditional dance performance during Kannada Rajyotsava at TACS" },
        { label: "Art & Craft", height: 300, src: "images/home/gallery/extra-1.png", alt: "Students sketching during an art and craft session at TACS" },
        { label: "Music Practice", height: 200, src: "images/home/gallery/extra-4.png", alt: "Students practising music in the campus studio at TACS" },
      ],
    },
    {
      id: "boarding",
      label: "Boarding Life",
      items: [
        { label: "Hostel Life", height: 180, src: "images/home/gallery/boarding-8.png", alt: "Dorm parent interacting with students in the hostel at TACS", objectPosition: "12% center" },
        { label: "Hostel Study", height: 320, src: "images/home/gallery/boarding-3.png", alt: "Students studying together in a hostel room at TACS" },
        { label: "Evening Campus Life", height: 280, src: "images/home/gallery/boarding-5.png", alt: "Students spending time together on campus in the evening at TACS" },
        { label: "Student Community", height: 220, src: "images/home/gallery/boarding-4.png", alt: "Students socialising together on campus at TACS" },
        { label: "Campus Corridors", height: 200, src: "images/home/gallery/boarding-2.png", alt: "Students in the hostel corridors at TACS", objectPosition: "48% 52%" },
        { label: "Outdoor Activities", height: 300, src: "images/home/gallery/boarding-6.png", alt: "Students enjoying outdoor activities on campus at TACS" },
        { label: "Dining Experience", height: 240, src: "images/home/gallery/boarding-7.png", alt: "Students in the dining hall at TACS" },
        { label: "Pastoral Care", height: 260, src: "images/home/gallery/boarding-1.png", alt: "Pastoral care staff supporting students at TACS" },
      ],
    },
  ],
};
